#!/bin/sh
action="push"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
WORKNAME=$(git log -1 --pretty=format:%s)

MSG="[$action] - [$BRANCH] - [$WORKNAME]"

# Ghi log để check script có chạy
echo "$MSG" >> "$(dirname "$0")/hook.log"

# Gửi sang Discord
java -cp "E:/FPT_document/Student_marterials/Ky_CN_5/SWP391/SWP391_Project/DiscordNotifier/discord-notifier.jar" DiscordNotifier "$MSG"

# Chạy git push thật
exec git push "$@"
