#!/bin/sh
action="pull"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
WORKNAME=$(git log -1 --pretty=format:%s)

MSG="[$action] - [$BRANCH] - [$WORKNAME]"

echo "$MSG" >> "$(dirname "$0")/hook.log"

java -cp "E:/FPT_document/Student_marterials/Ky_CN_5/SWP391/SWP391_Project/DiscordNotifier/discord-notifier.jar" DiscordNotifier "$MSG"

# Chạy git pull thật
exec git pull "$@"
